
[window]
dynamic_padding = true
decorations = "Full"
opacity = 0.9
dynamic_title = true
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[scrolling]
history = 10000

[font]
# normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
size = 12

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.primary]
foreground = "#dfdfdf"
bright_foreground = "#ffffff"

[keyboard]
bindings = [
    {key = "Left", mods = "Alt", chars = "\u001B[1;3D"},
    {key = "Right", mods = "Alt", chars = "\u001B[1;3C"},
]

[mouse]
hide_when_typing =  true

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
shell = "/bin/zsh"
