#!/usr/bin/env zsh

WORKSPACE=~/work/code

selected=$(find ~/work/code ~/dotfiles -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

echo "Selected project: $selected"

# Name of the directory
selected_name=$(basename "$selected" | tr . _)
echo "tmux session name: $selected"

# Check running tmux sessions
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "tmux is not running, creating new session for $selected"
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    echo "tmux session $selected_name does not exist, creating new session for $selected"
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -n "$TMUX" ]]; then
    echo "We are already inside tmux session"
    echo "Switching to $selected_name"
    tmux switch-client -t $selected_name
else
    echo "We are not inside a tmux session"
    echo "attaching to $selected_name"
    tmux attach-session -t $selected_name
fi

echo "Attaching to $selected_name"
